### ISSUE TITLE
support of docker

### ISSUE THREAD

**Issue by weihangChen** [Azure-Samples/Blockchain-Ethereum-Template#14]
hi guys

maybe it will be good to have docker support? So the required installation can be set up easiler.
dockerfile

```
FROM node

RUN apt-get update & apt-get install python3
RUN npm install -g ganache-cli 
#modify access so truffle can be installed
RUN chmod -R 777 root
RUN npm install -g truffle

```

docker-compose.yml

```
version: '3'
services:
  bc:
    image: **
    container_name: **
    ports: 
      - "8545:8545"
    volumes: 
      - "./:/workdir"
    privileged: true
    command: /bin/bash -c "ganache-cli"
```
